version: "3.8"

x-server-port: &server-port
  8000

x-common-variables: &common-variables
  MYSQL_USER: powercoders
  MYSQL_PASSWORD: mypower1234
  MYSQL_DATABASE: powercoders-demo
  SERVER_PORT: *server-port

services:
  mysql-db:
    image: mysql:5.7
    container_name: powercoders_mysql
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: powercoders_mysqladmin
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    container_name: powercoders_server
    image: mifrugo/powercoders_server
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    links:
      - mysql-db
    command: npm start
  client:
    build: ./client
    container_name: powercoders_client
    image: mifrugo/powercoders_client
    environment:
      NODE_PATH: src
      REACT_APP_SERVER_PORT: *server-port
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start
